spring:
  datasource:
    url: jdbc:sqlserver://galaxiadb.database.windows.net:1433;database=galaxiaDb;encrypt=true;trustServerCertificate=false;hostNameInCertificate=*.database.windows.net;loginTimeout=30;
    username: sofija
    password: test123!
  jpa:
    hibernate:
      ddl-auto: update
      dialect: org.hibernate.dialect.SQLServer2012Dialect
    show-sql: true

server:
  port: 9090